# Generated by Django 6.1 on 2026-09-19 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0001_initial'),
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionrecord',
            name='appointment',
            field=models.ForeignKey(blank=True, help_text='Confirmed onsite visit this adoption record was scheduled from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adoption_records', to='appointments.appointment'),
        ),
    ]
