# Generated by Django 6.1 on 2026-09-18 04:43

import apps.appointments.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('pets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_date', models.DateField(validators=[apps.appointments.models.validate_visit_date])),
                ('status', models.CharField(choices=[('pending_confirmation', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending_confirmation', max_length=32)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Why the requested date was rejected - visible to the adopter')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adopter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='applications.application')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='pets.pet')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['pending_confirmation', 'confirmed'])), fields=('application',), name='unique_active_appointment_per_application')],
            },
        ),
    ]
