# Generated by Django 6.1 on 2026-09-02 10:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('pending_documents', 'Pending Documents'), ('additional_info_requested', 'Additional Info Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('adoption_completed', 'Adoption Completed')], default='draft', max_length=30)),
                ('why_adopt', models.TextField(blank=True, help_text='Why do you want to adopt this pet?')),
                ('experience_with_pets', models.TextField(blank=True, help_text='Describe your experience with pets')),
                ('living_situation', models.TextField(blank=True, help_text='Describe your living situation')),
                ('has_other_pets', models.BooleanField(default=False)),
                ('other_pets_description', models.TextField(blank=True)),
                ('references', models.TextField(blank=True, help_text='Personal or veterinary references')),
                ('additional_notes', models.TextField(blank=True)),
                ('staff_notes', models.TextField(blank=True, help_text='Internal staff notes - not visible to adopter')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adopter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='pets.pet')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['cancelled', 'rejected', 'adoption_completed']), _negated=True), fields=('adopter', 'pet'), name='unique_active_application_per_adopter_pet')],
            },
        ),
    ]
