# Generated by Django 6.1 on 2026-09-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(blank=True, help_text='Actual date the onsite payment was made', null=True),
        ),
    ]
